algoritmo "VOLEI"
// Função : calcular idade para jogar
// Autor :
// Data : 22/06/2020
// Seção de Declarações 
var
tamanho:real
idade:inteiro

inicio
//entrada
 escreval("qual sua idade?")
 leia(idade)
 
 escreval("qual seu tamanho?")
 leia(tamanho)

 //decisao
 
 se ((idade>=18)ou(altura>=1.75)) entao
 escreval("PERMITIDO")
 senao
 escreval("NAO ESTA PERMITIDO")
 fimse
fimalgoritmo
